### ISSUE TITLE
Missing configuration default when upgrading from 3.4.3 to 3.5.x

### ISSUE THREAD

**Issue by robert-scheck** [sbidy/MacroMilter#39]
When upgrading from MacroMilter 3.4.3 to 3.5.x without changing the `config.ini`, the daemon fails as follows due to a missing configuration default if unset:

```
May 11 00:32:34 tux macromilter: Traceback (most recent call last):
May 11 00:32:34 tux  macromilter: File "/usr/bin/macromilter", line 105, in <module>
May 11 00:32:34 tux  macromilter: UMASK = int(config.get('Milter', 'UMASK'), base=0)
May 11 00:32:34 tux  macromilter: File "/usr/lib64/python2.7/ConfigParser.py", line 618, in get
May 11 00:32:34 tux  macromilter: raise NoOptionError(option, section)
May 11 00:32:34 tux  macromilter: ConfigParser.NoOptionError: No option 'umask' in section: 'Milter'
```

**Comment by sbidy** [comment]
Merged and reviewed.

**Comment by robert-scheck** [comment]
@sbidy, do you see a chance to create a tag/release including this fix? This would help to get a current version of MacroMilter into Fedora and EPEL.
